### PR TITLE
~/.local/bin/ not available on Mac, pip3 installs twint to /usr/local/bin/

### PR DESCRIPTION
**Pull request by jeffp42ker**
This fix works for Mac development. I haven't deployed to Unbuntu to test, just pointing out ~/.local seems env specific?

### CODE REVIEW

**Comment by jacobobryant** [comment]
Sorry for the delay, I saw this last weekend and was planning to reply on monday but it totally slipped my mind until just now!

It might be env specific; at a minimum it depends on installing the python package as a user vs. as the system. This would break the app in production for anyone who uses the setup script, since that installs the package as a user (https://github.com/jacobobryant/hallway/blob/master/infra/setup.sh#L105). We could change the script to install it system-wide, but I do like being able to install it as a user in dev.

I wonder if there's an easy way to just figure out at runtime where the binary has been installed to? e.g. if there's a pip command to list files in a package, we could do that and then grep for bin/twint or something.

**Comment by jacobobryant** [comment]
Or perhaps instead, we just say "make sure you have twint on the path" in the readme for dev, change the setup script to install to the system, make sure that puts twint on the path (and fix it if not), then change this call to just call twint without the absolute path

**Comment by jeffp42ker** [comment]
This issue goes away simply by developing within a linux vm (as I should have been doing). Thanks.

**Comment by jacobobryant** [comment]
Sounds good. If you/anyone else would like to make this work for Mac dev in the future I'd be happy to accept a PR. Just made an issue: https://github.com/jacobobryant/hallway/issues/12

**Pull request closed without merging**
